name: Build Wheel for py12

# 触发条件：手动触发或标签推送
on:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build wheel
    runs-on: windows-latest

    steps:
      # 步骤1：签出代码
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "false"

      # 步骤2：设置Python环境
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      # 步骤3：安装依赖
      - name: Install dependencies
        run: |
          powershell (new-object System.Net.WebClient).DownloadFile('https://files.pythonhosted.org/packages/87/cb/006cbc9c06de9fafdd8182e1a38d793d89ee89b48eab052053b3e5cb2ddf/cpufeature-0.2.1.tar.gz','cpufeature-0.2.1.tar.gz')
          .\assets\binary\7za.exe x -y -aos cpufeature-0.2.1.tar.gz
          .\assets\binary\7za.exe x -y -aos cpufeature-0.2.1.tar -ocpufeature
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 步骤4：生成程序
      - name: Generate wheel
        run: |
          
          
          pip wheel .\cpufeature\cpufeature-0.2.1\
          .\assets\binary\7za.exe a -tzip .\cpufeature\cpufeature-0.2.1\build.zip c:\users\runneradmin\appdata\local\pip\cache\wheels

      # 步骤7：上传压缩包
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpufeature-0.2.1.zip
          path: ./cpufeature/cpufeature-0.2.1/build.zip
          compression-level: 0 # no compression